modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://minecraft.curseforge.com/projects/drp-global-datapack/issues"
license="ARR"

[[mods]]
	modId="globaldataandresourcepacks"
	version="1.8"
	displayName="Global Data- & Resourcepacks"
	displayURL="https://minecraft.curseforge.com/projects/drp-global-datapack"
	authors="JTK222"
	description='''Allows modpacks to add Datapacks & Resource Packs, both are force enabled'''

[[dependencies]]
	modId="forge"
	mandatory=true
	versionRange="[32,)"
	ordering="NONE"
	side="BOTH"

[[dependencies]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.16,)"
	ordering="NONE"
	side="BOTH"
